#!/bin/sh
(cd "/Users/mertnuhoglu/Dropbox/baku"; tree | sed 's/├\|─\|│\|└\| / /g' | sed 's/    /\t/g' > "/Users/mertnuhoglu/Dropbox (BTG)/TEUIS PROJECT 50-PROJECT MANAGEMENT/draft/file_tree.otl")
(cd "/Users/mertnuhoglu/Dropbox (BTG)"; tree | sed 's/├\|─\|│\|└\| / /g' | sed 's/    /\t/g' >> "/Users/mertnuhoglu/Dropbox (BTG)/TEUIS PROJECT 50-PROJECT MANAGEMENT/draft/file_tree.otl")
