#!/bin/bash
#MP4FILE=$(ls . | grep .mp4)
#for filename in $MP4FILE
find . -iname "*.mp4" | while read filename
do 
 name=`echo "$filename" | sed -e "s/.mp4$//g"`
 ffmpeg -i "$filename" -b:a 192K -vn "$name.mp3"
done
